# Minimal conda environment with python, pip and poetry and windows Make file support.
# Dependencies are managed by Poetry
name: ocx-databinding
channels:
  - conda-forge
  - msys2 # for m2-grep
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - poetry
  - pip:
      - xsdata[cli,lxml, soap]  # xsdata with all dependencies
